include:
  - project: 'gitlab/templates/containers'
    ref: main
    file: '/default.yml'


.docker_login_template: &docker_login
  before_script:
    # Group login incase we need to pull group images from a private registry
    - |
      if [ -n "$GROUP_CI_REGISTRY_USER" -a -n "$GROUP_CI_REGISTRY_PASSWORD" ]; then
        echo "Group CI login to '${GROUP_CI_REGISTRY}'...";
        echo "$GROUP_CI_REGISTRY_PASSWORD" | docker login --username "$GROUP_CI_REGISTRY_USER" --password-stdin "$GROUP_CI_REGISTRY";
      fi
    # Login to this repositories registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"


test-uvicorn:
  <<: *docker_login
  stage: test
  script:
    - |
      set -x
      echo "Pulling '$PIPELINE_IMAGE'..."
      docker pull "$PIPELINE_IMAGE"
      docker run -e FDC_CI=true -e GUNICORN_WORKER_CLASS=uvicorn.workers.UvicornWorker "$PIPELINE_IMAGE"
      set +x
